#!/bin/bash
set -e

if [ "$1" == "-f" ]; then
    CMD="xargs git branch -d "
else
    echo "Feature branches already merged into $(git rev-parse --abbrev-ref HEAD) (use -f to remove these):"
    CMD=cat
fi

git branch --merged | grep -v "\(master\|develop\|next\|integration\)" | $CMD
