#!/bin/bash

# Creates a new branch with a clean history, useful when starting
# from a prototype. Same effect as branching and then squashing all but one commit.

branch_name=$1

if [ $branch_name == "" ]; then
    echo "You must specify a branch name"
else
    git branch $branch_name $(echo "Initial commit" | git commit-tree HEAD^{tree})
fi

