#!/bin/bash

if [ ! -z $1 ]; then
    mainbranch="$1"
else
    mainbranch="develop"
fi

# Assumes that feature branches are always branched off 'develop'
# Send in a branch as argument to use another branch to compare to.
git rebase -i --autosquash `git merge-base HEAD $mainbranch`
