#!/bin/bash

if [ "$(id -u)" != "0" ]; then
    echo "You need to be root"
    exit 1
fi

for f in $(ls git-*)
do
  echo "Installing $f"
  if [ ! -f /usr/local/bin/$f ]; then
    ln -s $(pwd)/$f /usr/local/bin/$f
  fi
done

