#!/bin/bash
set -e

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

echo 'export PATH="$PATH:'"$DIR" >> ~/.zshrc

echo "Installing latest stable version of git"
sudo add-apt-repository -y ppa:git-core/ppa
sudo apt -y update
sudo apt -y install git

create() {

if [ ! -f ~/.ssh/$1 ]; then
  echo "Creating an ssh key for $1. Protect it with a passphrase."
  ssh-keygen -t rsa -C "${HOSTNAME}/$1" -b 4096 -f ~/.ssh/$1
fi

chmod 600 ~/.ssh/$1

}

create github_com
create gitlab_com

# Copying config
cp $DIR/_gitconfig ~/.gitconfig

