#!/bin/bash

if [ "$(id -u)" != "0" ]; then
    echo "You need to be root"
    exit 1
fi

for f in $(ls git-*)
do
  echo "Installing $f"
  cp -f "$(pwd)/$f" "/usr/local/bin/$f"
done

echo "Installing ~/.gitconfig..."
cp ./_gitconfig ~/.gitconfig

echo "Installing diff-so-fancy..."
npm install -g diff-so-fancy

