#!/bin/bash

set -e

sudo apt install -y curl net-tools scrot

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
cd $DIR

./git/install
./zsh/install
./fzf/install
./ag/install
./docker/install
./mutt/install

