#!/bin/bash
set -e

if ! command -v vim; then
  sudo apt install -y vim
fi

cp -f ./vimrc ~/.vimrc
mkdir -p ~/.vim/colors
cp ./_vim/colors/distinguished.vim ~/.vim/colors/

# Install the vundle plugin (package management)
if [ ! -d ~/.vim/bundle/Vundle.vim ]; then
  echo "Installing Vundle.vim from github..."
  git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
else
  echo "Vundle.vim already exists in ~/.vim/bundle"
fi

# Ensure that the .profile file is correct (it exports the TERM=xterm-256color)
cp ../shell/.profile ~/.profile

echo "Installing all registered plugins..."
vim +PluginInstall +qall

