#!/bin/bash
set -e

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
cd $DIR

# Installs neovim

if ! command -v nvim $> /dev/null
then
sudo apt -y install neovim
sudo apt -y install python-neovim
sudo apt -y install python3-neovim
fi

# Install plugin manager (plug.vim)

if [ ! -f ~/.nvim/plug.vim ]; then
curl -fLo ~/.nvim/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi


cp ./vimrc ~/.config/nvim/init.vim

vim +PlugInstall +qall

# virtualenvs for neovim's py interpreters

pyenv install 2.7.18
pyenv virtualenv 2.7.18 neovim2
pyenv activate neovim2
pip install neovim

pyenv install 3.8.5
pyenv virtualenv 3.8.5 neovim3
pyenv activate neovim3
pip install neovim
