#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
cd $DIR

cp _tmux.conf ~/.tmux.conf
sudo apt install tmux

git clone --depth=1 https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
